./src/redis-benchmark -q -c 4 -n 100000 msetnx \
key_abcdefghijklmnopqrstuvwxyz_001	val_abcdefghijklmnopqrstuvwxyz_001	\
key_abcdefghijklmnopqrstuvwxyz_002	val_abcdefghijklmnopqrstuvwxyz_002	\
key_abcdefghijklmnopqrstuvwxyz_003	val_abcdefghijklmnopqrstuvwxyz_003	\
key_abcdefghijklmnopqrstuvwxyz_004	val_abcdefghijklmnopqrstuvwxyz_004	\
key_abcdefghijklmnopqrstuvwxyz_005	val_abcdefghijklmnopqrstuvwxyz_005	\
key_abcdefghijklmnopqrstuvwxyz_006	val_abcdefghijklmnopqrstuvwxyz_006	\
key_abcdefghijklmnopqrstuvwxyz_007	val_abcdefghijklmnopqrstuvwxyz_007	\
key_abcdefghijklmnopqrstuvwxyz_008	val_abcdefghijklmnopqrstuvwxyz_008